//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoGame2D.Example {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleSceneResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleSceneResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonoGame2D.Example.ExampleSceneResource", typeof(ExampleSceneResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] c0000 {
            get {
                object obj = ResourceManager.GetObject("c0000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0001 {
            get {
                object obj = ResourceManager.GetObject("c0001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0002 {
            get {
                object obj = ResourceManager.GetObject("c0002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0003 {
            get {
                object obj = ResourceManager.GetObject("c0003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0004 {
            get {
                object obj = ResourceManager.GetObject("c0004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0005 {
            get {
                object obj = ResourceManager.GetObject("c0005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0006 {
            get {
                object obj = ResourceManager.GetObject("c0006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0007 {
            get {
                object obj = ResourceManager.GetObject("c0007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0008 {
            get {
                object obj = ResourceManager.GetObject("c0008", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] c0009 {
            get {
                object obj = ResourceManager.GetObject("c0009", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lava {
            get {
                object obj = ResourceManager.GetObject("lava", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
